___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [4]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [7]:
my_list = [5, 10, 15, 20, 25]
np.array([my_list])

array([[ 5, 10, 15, 20, 25]])

#### 3. Generate an array of 5x5 with zeros 

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [9]:
np.ones((4, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [16]:
my_arr = np.ones((4, 4), dtype=int)
np.place(my_arr, my_arr == 1, 7)
my_arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [11]:
np.full((4, 4), 7, dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [19]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [21]:
np.array([range(25)]).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [28]:
np.linspace(0,24,25).reshape(5,5)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

#### 10. Create randomly 5 numbers with numpy

In [32]:
np.random.randint(0, 100, 5)

array([ 5, 86, 71, 18, 40])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [33]:
np.random.rand(5,5)

array([[0.17957039, 0.09866432, 0.11182501, 0.01873196, 0.1578642 ],
       [0.11592402, 0.35009711, 0.0542959 , 0.64025312, 0.31929192],
       [0.03159372, 0.70028624, 0.65857701, 0.70888154, 0.90067158],
       [0.11556219, 0.76326817, 0.82533476, 0.4076604 , 0.62320157],
       [0.38407764, 0.56702741, 0.49243627, 0.78797656, 0.11236765]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [35]:
np.random.randint(20,51, size=(3,4))

array([[26, 41, 35, 28],
       [29, 50, 50, 36],
       [47, 41, 28, 32]])

#### 13. Reshape the array below with the shape of 6x8

In [37]:
ranarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [40]:
ranarr.reshape(6, 8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [42]:
#reshape with -1
ranarr.reshape(-1)

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

## Numpy Indexing and Selection


In [58]:
#Create array below
mat= np.array([range(1, 17)]).reshape(4,4) 
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [50]:
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [52]:
mat[::,1]

array([ 2,  6, 10, 14])

#### 16. Get the values in 2nd row for every 2 step.

In [53]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
mat[1:2,0::2]

array([[5, 7]])

#### 17.Assign 77 to every cell in 3rd column.

In [59]:
mat[::,2:3]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [62]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [65]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [33]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [67]:
mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [68]:
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [69]:
mat[mat < 10] + mat[mat > 12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [72]:
a = mat[mat < 10] + mat[mat > 12]
a.std()

29.700546274093877

#### 22. Get the sum of the second column from array above

In [75]:
#print array here
mat[::,1:2]

array([[ 2],
       [ 6],
       [10],
       [14]])

In [76]:
mat[::,1:2].sum()

32

#### 23. Get the median, mean and std of 3rd row from array above

In [81]:
mat = np.array([range(1, 17)]).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
mat[2:3, ::]

array([[ 9, 10, 11, 12]])

In [98]:
#median
np.median(mat[2:3, ::])

10.5

In [96]:
#mean
mat[2:3, ::].mean()

10.5

In [97]:
#std
mat[2:3, ::].std()

1.118033988749895

# Pandas Section

In [99]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [100]:
sal=pd.read_csv('Salaries.csv')

In [101]:
sal.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [103]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [104]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

**How many different year values are there?**

In [111]:
sal.nunique()

Id                  148654
EmployeeName        110811
JobTitle              2159
BasePay             109489
OvertimePay          65998
OtherPay             83225
Benefits             98465
TotalPay            138486
TotalPayBenefits    142098
Year                     4
Notes                    0
Agency                   1
Status                   0
dtype: int64

In [112]:
sal.groupby("Year").size()

Year
2011    36159
2012    36766
2013    37606
2014    38123
dtype: int64

**Print out max and avg Totalpay**

In [114]:
#max
sal["TotalPay"].max()

567595.43

In [118]:
#avg
sal["TotalPay"].mean()

74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [122]:
sal["TotalPay"][sal["TotalPay"] > sal["TotalPay"].mean()]

0         567595.43
1         538909.28
2         335279.91
3         332343.61
4         326373.19
            ...    
135701     77186.02
135778     76746.22
135847     76305.74
135853     76280.70
136063     74893.70
Name: TotalPay, Length: 69489, dtype: float64

In [123]:
len(sal["TotalPay"][sal["TotalPay"] > sal["TotalPay"].mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [124]:
sal.groupby("EmployeeName").head()

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148544 rows x 13 columns]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

In [150]:
sal.sort_values(by="TotalPay")

Id           EmployeeName  \
148653  148654              Joe Lopez   
106745  106746        Tiffany M Rasso   
106746  106747       Bertha  Robinson   
106747  106748       Kermith T Miller   
106748  106749  Rita I Sinasohn-Pharr   
...        ...                    ...   
36159    36160         Gary Altenberg   
110532  110533             Amy P Hart   
110531  110532            David Shinn   
1            2           GARY JIMENEZ   
0            1         NATHANIEL FORD   

                                              JobTitle    BasePay  \
148653                      Counselor, Log Cabin Ranch       0.00   
106745                             Recreation Director        NaN   
106746                                Transit Operator        NaN   
106747                                 Utility Plumber        NaN   
106748                                    Clerk Typist        NaN   
...                                                ...        ...   
36159                     Lieutenant, Fire Suppression  128808.87   
110532                               Asst Med Examiner  318835.49   
110531                                  Deputy Chief 3  129150.01   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
148653         0.00    -618.13      0.00    -618.13           -618.13  2014   
106745         0.00       0.00   7959.18       0.00           7959.18  2013   
106746         0.00       0.00   7959.18       0.00           7959.18  2013   
106747         0.00       0.00   7959.18       0.00           7959.18  2013   
106748         0.00       0.00   7959.18       0.00           7959.18  2013   
...             ...        ...       ...        ...               ...   ...   
36159     220909.48   13126.31  44430.12  362844.66         407274.78  2012   
110532     10712.95   60563.54  89540.23  390111.98         479652.21  2014   
110531         0.00  342802.63  38780.04  471952.64         510732.68  2014   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
0              0.00  400184.25       NaN  567595.43         567595.43  2011   

        Notes         Agency  Status  
148653    NaN  San Francisco     NaN  
106745    NaN  San Francisco     NaN  
106746    NaN  San Francisco     NaN  
106747    NaN  San Francisco     NaN  
106748    NaN  San Francisco     NaN  
...       ...            ...     ...  
36159     NaN  San Francisco     NaN  
110532    NaN  San Francisco     NaN  
110531    NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
0         NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [155]:
sal.groupby("JobTitle").size()

JobTitle
ACCOUNT CLERK                                      83
ACCOUNTANT                                          5
ACCOUNTANT INTERN                                  48
ACPO,JuvP, Juv Prob (SFERS)                         1
ACUPUNCTURIST                                       1
                                                 ... 
X-RAY LABORATORY AIDE                              26
X-Ray Laboratory Aide                             100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS      1
Youth Comm Advisor                                  4
ZOO CURATOR                                         1
Length: 2159, dtype: int64

**What are the unique Jobs in dataset?**

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

In [170]:
sal[sal["Year"] == 2012][sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()]

/tmp/ipykernel_4540/4213234113.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sal[sal["Year"] == 2012][sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()]


Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
56520  56521        Sue Madrigal     Senior Eligibility Worker   63841.94   
56521  56522   Concepcion Gruber                   Secretary 2   61996.06   
56522  56523         Kerman Chan       Parking Control Officer   55358.50   
56523  56524      Ramon Lafuente       Parking Control Officer   56006.80   
56524  56525      Lai Ping Szeto            Eligibility Worker   61253.05   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
56520         0.00    568.66  29305.51   64410.60          93716.11  2012   
56521      1111.50    624.00  29981.74   63731.56          93713.30  2012   
56522      8539.77   1231.25  28579.83   65129.52          93709.35  2012   
56523      6326.45   2175.24  29192.61   64508.49          93701.10  2012   
56524       988.54   1460.00  29996.77   63701.59          93698.36  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
56520    NaN  San Francisco     NaN  
56521    NaN  San Francisco     NaN  
56522    NaN  San Francisco     NaN  
56523    NaN  San Francisco     NaN  
56524    NaN  San Francisco     NaN  

[20366 rows x 13 columns]

In [172]:
sal[sal["Year"] == 2012][sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()].describe()

/tmp/ipykernel_4540/1931338655.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sal[sal["Year"] == 2012][sal["TotalPayBenefits"] > sal["TotalPayBenefits"].mean()].describe()


Id        BasePay    OvertimePay       OtherPay  \
count  20366.000000   20366.000000   20366.000000   20366.000000   
mean   46342.500000   94711.369393    8362.764014    5560.345145   
std     5879.302127   29386.722674   14383.478851    9863.530527   
min    36160.000000       0.000000       0.000000       0.000000   
25%    41251.250000   71264.607500       0.000000     393.082500   
50%    46342.500000   88374.020000    2055.520000    2613.690000   
75%    51433.750000  110847.130000   11008.707500    7621.907500   
max    56525.000000  302578.000000  220909.480000  245999.410000   

           Benefits       TotalPay  TotalPayBenefits     Year  Notes  Status  
count  20366.000000   20366.000000      20366.000000  20366.0    0.0     0.0  
mean   37526.563389  108634.478552     146161.041941   2012.0    NaN     NaN  
std     7618.301188   36745.635863      41685.359420      0.0    NaN     NaN  
min      171.410000   60627.610000      93698.360000   2012.0    NaN     NaN  
25%    33013.570000   79389.525000     112624.855000   2012.0    NaN     NaN  
50%    36464.480000   98900.365000     135908.305000   2012.0    NaN     NaN  
75%    40537.912500  129374.665000     169741.317500   2012.0    NaN     NaN  
max    84681.820000  362844.660000     407274.780000   2012.0    NaN     NaN

20366

**How many people have a title of Manager in their jobs?**

In [178]:
sal["JobTitle"].apply(lambda x: True if Sal[x] == "Manager")

SyntaxError: invalid syntax (2771214747.py, line 1)

In [71]:
#use apply function here


4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [201]:
sal_new = sal.iloc[:: , [2,7,8]]
sal_new

JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 3 columns]

In [72]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [75]:
sal_new=
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___